import type { FoodInput } from '../src/types/food.js';

// Approximate values per 100 g edible portion for demonstration purposes.
export const seedFoodData = [
  { name: 'Apple', category: 'Fruit', servingSize: 100, nutrition: { calories: 52, protein: 0.3, carbohydrates: 13.8, fat: 0.2, fiber: 2.4 } },
  { name: 'Banana', category: 'Fruit', servingSize: 100, nutrition: { calories: 89, protein: 1.1, carbohydrates: 22.8, fat: 0.3, fiber: 2.6 } },
  { name: 'Orange', category: 'Fruit', servingSize: 100, nutrition: { calories: 47, protein: 0.9, carbohydrates: 11.8, fat: 0.1, fiber: 2.4 } },
  { name: 'Mango', category: 'Fruit', servingSize: 100, nutrition: { calories: 60, protein: 0.8, carbohydrates: 15, fat: 0.4, fiber: 1.6 } },
  { name: 'Guava', category: 'Fruit', servingSize: 100, nutrition: { calories: 68, protein: 2.6, carbohydrates: 14.3, fat: 1, fiber: 5.4 } },
  { name: 'Spinach', category: 'Vegetable', servingSize: 100, nutrition: { calories: 23, protein: 2.9, carbohydrates: 3.6, fat: 0.4, fiber: 2.2 } },
  { name: 'Broccoli', category: 'Vegetable', servingSize: 100, nutrition: { calories: 34, protein: 2.8, carbohydrates: 6.6, fat: 0.4, fiber: 2.6 } },
  { name: 'Carrot', category: 'Vegetable', servingSize: 100, nutrition: { calories: 41, protein: 0.9, carbohydrates: 9.6, fat: 0.2, fiber: 2.8 } },
  { name: 'Tomato', category: 'Vegetable', servingSize: 100, nutrition: { calories: 18, protein: 0.9, carbohydrates: 3.9, fat: 0.2, fiber: 1.2 } },
  { name: 'Sweet Potato, Cooked', category: 'Vegetable', servingSize: 100, nutrition: { calories: 90, protein: 2, carbohydrates: 20.7, fat: 0.2, fiber: 3.3 } },
  { name: 'Basmati Rice, Cooked', category: 'Grain', servingSize: 100, nutrition: { calories: 130, protein: 2.7, carbohydrates: 28.2, fat: 0.3, fiber: 0.4 } },
  { name: 'Brown Rice, Cooked', category: 'Grain', servingSize: 100, nutrition: { calories: 123, protein: 2.7, carbohydrates: 25.6, fat: 1, fiber: 1.6 } },
  { name: 'Quinoa, Cooked', category: 'Grain', servingSize: 100, nutrition: { calories: 120, protein: 4.4, carbohydrates: 21.3, fat: 1.9, fiber: 2.8 } },
  { name: 'Oats, Dry', category: 'Grain', servingSize: 100, nutrition: { calories: 389, protein: 16.9, carbohydrates: 66.3, fat: 6.9, fiber: 10.6 } },
  { name: 'Whole Wheat Bread', category: 'Grain', servingSize: 100, nutrition: { calories: 247, protein: 13, carbohydrates: 41, fat: 4.2, fiber: 7 } },
  { name: 'Whole Wheat Roti', category: 'Indian', servingSize: 100, nutrition: { calories: 297, protein: 9.7, carbohydrates: 55.8, fat: 4.2, fiber: 9.8 } },
  { name: 'Dal, Cooked', category: 'Indian', servingSize: 100, nutrition: { calories: 116, protein: 9, carbohydrates: 20, fat: 0.4, fiber: 7.9 } },
  { name: 'Rajma, Cooked', category: 'Indian', servingSize: 100, nutrition: { calories: 127, protein: 8.7, carbohydrates: 22.8, fat: 0.5, fiber: 6.4 } },
  { name: 'Chana Masala', category: 'Indian', servingSize: 100, nutrition: { calories: 164, protein: 7.5, carbohydrates: 27, fat: 3.5, fiber: 7.6 } },
  { name: 'Idli', category: 'Indian', servingSize: 100, nutrition: { calories: 146, protein: 4.5, carbohydrates: 29, fat: 0.7, fiber: 1.5 } },
  { name: 'Dosa, Plain', category: 'Indian', servingSize: 100, nutrition: { calories: 184, protein: 4.5, carbohydrates: 30.7, fat: 4.8, fiber: 1.1 } },
  { name: 'Poha, Cooked', category: 'Indian', servingSize: 100, nutrition: { calories: 130, protein: 2.6, carbohydrates: 25, fat: 2.5, fiber: 1.8 } },
  { name: 'Upma, Cooked', category: 'Indian', servingSize: 100, nutrition: { calories: 119, protein: 3.5, carbohydrates: 20, fat: 3, fiber: 2 } },
  { name: 'Paneer', category: 'Dairy', servingSize: 100, nutrition: { calories: 265, protein: 18.3, carbohydrates: 1.2, fat: 20.8, fiber: 0 } },
  { name: 'Whole Milk', category: 'Dairy', servingSize: 100, nutrition: { calories: 61, protein: 3.2, carbohydrates: 4.8, fat: 3.3, fiber: 0 } },
  { name: 'Greek Yogurt, Plain', category: 'Dairy', servingSize: 100, nutrition: { calories: 97, protein: 9, carbohydrates: 3.9, fat: 5, fiber: 0 } },
  { name: 'Tofu, Firm', category: 'Protein', servingSize: 100, nutrition: { calories: 144, protein: 17.3, carbohydrates: 2.8, fat: 8.7, fiber: 2.3 } },
  { name: 'Chickpeas, Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 164, protein: 8.9, carbohydrates: 27.4, fat: 2.6, fiber: 7.6 } },
  { name: 'Lentils, Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 116, protein: 9, carbohydrates: 20.1, fat: 0.4, fiber: 7.9 } },
  { name: 'Chicken Breast, Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 165, protein: 31, carbohydrates: 0, fat: 3.6, fiber: 0 } },
  { name: 'Whole Egg, Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 155, protein: 12.6, carbohydrates: 1.1, fat: 10.6, fiber: 0 } },
  { name: 'Salmon, Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 206, protein: 22.1, carbohydrates: 0, fat: 12.4, fiber: 0 } },
  { name: 'Tuna, Canned in Water', category: 'Protein', servingSize: 100, nutrition: { calories: 116, protein: 25.5, carbohydrates: 0, fat: 0.8, fiber: 0 } },
  { name: 'Mutton, Lean Cooked', category: 'Protein', servingSize: 100, nutrition: { calories: 250, protein: 25, carbohydrates: 0, fat: 16, fiber: 0 } },
  { name: 'Almonds', category: 'Nuts', servingSize: 100, nutrition: { calories: 579, protein: 21.2, carbohydrates: 21.6, fat: 49.9, fiber: 12.5 } },
  { name: 'Peanuts, Roasted', category: 'Nuts', servingSize: 100, nutrition: { calories: 587, protein: 24.4, carbohydrates: 21.3, fat: 49.7, fiber: 8.4 } },
] satisfies FoodInput[];

